/**
 * app.js — Punto de entrada principal de la aplicación
 * Inicializa el estado, registra todos los event listeners y arranca la app.
 */

// ============================================================
// ESTADO GLOBAL DE LA APLICACIÓN
// ============================================================
const state = {
  selected:       null,   // ID del ítem activo en el configurador
  options:        {},     // { [itemId]: { recipe: bool, loot: bool, inPack: bool } }
  activeCategory: 'all',
  activeTab:      'recipe',
  search:         ''
};

// Inicializar opciones por defecto para todos los ítems
ITEMS.forEach(item => {
  state.options[item.id] = { recipe: false, loot: false, inPack: false };
});

// ============================================================
// TOGGLES — Opciones del ítem seleccionado
// ============================================================
function toggleOption(name) {
  if (!state.selected) return;
  const opts = state.options[state.selected];
  if (name === 'recipe') opts.recipe = !opts.recipe;
  if (name === 'drop')   opts.loot   = !opts.loot;
  if (name === 'pack')   opts.inPack = !opts.inPack;

  setTrack('recipe', opts.recipe);
  setTrack('drop',   opts.loot);
  setTrack('pack',   opts.inPack);

  updatePreview(state.selected);
  renderList();
}

// ============================================================
// EVENT LISTENERS — Delegación de eventos (no onclick inline)
// ============================================================
document.addEventListener('DOMContentLoaded', () => {

  // Búsqueda en tiempo real
  document.getElementById('search-input').addEventListener('input', e => {
    state.search = e.target.value;
    renderList();
  });

  // Filtros de categoría
  document.querySelectorAll('.cat-pill').forEach(pill => {
    pill.addEventListener('click', () => {
      document.querySelectorAll('.cat-pill').forEach(p => p.classList.remove('active'));
      pill.classList.add('active');
      state.activeCategory = pill.dataset.cat;
      renderList();
    });
  });

  // Botones de selección masiva
  document.getElementById('btn-sel-all').addEventListener('click', () => {
    const q   = state.search.toLowerCase();
    const cat = state.activeCategory;
    ITEMS
      .filter(i => (cat === 'all' || i.cat === cat) &&
                   (i.name.toLowerCase().includes(q) || i.id.toLowerCase().includes(q)))
      .forEach(i => { state.options[i.id].inPack = true; });
    renderList();
  });

  document.getElementById('btn-clear-sel').addEventListener('click', () => {
    ITEMS.forEach(i => { state.options[i.id].inPack = false; });
    if (state.selected) setTrack('pack', false);
    renderList();
  });

  // Toggles del configurador
  document.getElementById('toggle-recipe').addEventListener('click', () => toggleOption('recipe'));
  document.getElementById('toggle-drop').addEventListener('click',   () => toggleOption('drop'));
  document.getElementById('toggle-pack').addEventListener('click',   () => toggleOption('pack'));

  // Give command
  document.getElementById('give-cmd').addEventListener('click', copyGiveCmd);

  // Botones de acciones rápidas
  document.getElementById('btn-download-recipe').addEventListener('click', downloadCurrentRecipe);
  document.getElementById('btn-download-loot').addEventListener('click',   downloadCurrentLoot);
  document.getElementById('btn-copy-json').addEventListener('click',       copyPreview);

  // Tabs de preview
  document.querySelectorAll('.preview-tab').forEach(btn => {
    btn.addEventListener('click', () => setTab(btn.dataset.tab));
  });

  // ============================================================
  // GENERAR PACK COMPLETO (ZIP)
  // ============================================================
  document.getElementById('btn-gen-pack').addEventListener('click', async () => {
    const packItems = ITEMS.filter(i => state.options[i.id].inPack);
    const packPokemons = Array.from(typeof POKEMON_STATE !== 'undefined' ? POKEMON_STATE.blocked : []);

    if (packItems.length === 0 && packPokemons.length === 0) {
      showToast('⚠️', 'Selecciona al menos 1 ítem o Pokémon para el Pack');
      return;
    }

    try {
      const zip = new JSZip();

      // pack.mcmeta
      const packMeta = {
        "pack": {
          "pack_format": PACK_FORMAT,
          "description": "§b⚡ §fCobblemon Datapack §b⚡\n§7Generated by Cobblemon Studio"
        }
      };

      const regexInput = document.getElementById('regex-filter-input');
      if (regexInput && regexInput.value.trim() !== '') {
        const val = regexInput.value.trim();
        let ns = ".*";
        let pth = val;
        
        if (val.includes(':')) {
           const parts = val.split(':');
           ns = parts[0];
           pth = parts.slice(1).join(':');
        }
        
        packMeta.filter = {
          "block": [
            {
              "namespace": ns,
              "path": pth
            }
          ]
        };
      }

      zip.file('pack.mcmeta', JSON.stringify(packMeta, null, 2));

      let recipeCount = 0;
      let dropCount   = 0;

      packItems.forEach(item => {
        const opts = state.options[item.id];

        if (opts.recipe) {
          zip.file(
            `data/${NAMESPACE}/recipes/${item.id}.json`,
            JSON.stringify(buildRecipeJSON(item.id), null, 2)
          );
          recipeCount++;
        }

        if (opts.loot) {
          zip.file(
            `data/${NAMESPACE}/species/overrides/${item.id}.json`,
            JSON.stringify(buildDropOverrideJSON(item.id), null, 2)
          );
          dropCount++;
        }

        // Si está en el pack pero sin toggles → añadir recipe por defecto
        if (!opts.recipe && !opts.loot) {
          zip.file(
            `data/${NAMESPACE}/recipes/${item.id}.json`,
            JSON.stringify(buildRecipeJSON(item.id), null, 2)
          );
          recipeCount++;
        }
      });
      
      // Inject Pokemon Blocks & Spawns
      let pkmnCount = 0;
      let pkmnBlockedCount = 0;
      let pkmnAllowedCount = 0;
      
      const pState = typeof POKEMON_STATE !== 'undefined' ? POKEMON_STATE : null;
      
      if (pState && typeof POKEMON_DB !== 'undefined') {
        POKEMON_DB.forEach(p => {
          const paddedDex = p.dex.toString().padStart(4, '0');
          const filename = `${paddedDex}_${p.id}.json`;
          const isBlocked = pState.blocked.has(p.dex);
          
          if (isBlocked) {
            zip.file(
              `data/${NAMESPACE}/spawn_pool_world/${filename}`,
              JSON.stringify({ "enabled": false }, null, 2)
            );
            pkmnBlockedCount++;
            pkmnCount++;
          } else {
            // Generar spawn avanzado para los permitidos
            const cfg = pState.overrides[p.dex] || pState.globalConfig || { level: "10-35", weight: 5.4, biomes: [] };
            let biomesArr = [];
            if (cfg.biomes && typeof cfg.biomes === 'string') {
              biomesArr = cfg.biomes.split('\n').map(b => b.trim()).filter(b => b.length > 0);
            } else if (Array.isArray(cfg.biomes)) {
              biomesArr = cfg.biomes;
            }
            
            const spawnConfig = {
              "enabled": true,
              "neededInstalledMods": [],
              "neededUninstalledMods": [],
              "spawns": [
                  {
                      "id": `${p.id}-1`,
                      "pokemon": p.id,
                      "presets": [
                          "natural",
                          "wild"
                      ],
                      "type": "pokemon",
                      "context": "grounded",
                      "bucket": "common",
                      "level": cfg.level,
                      "weight": parseFloat(cfg.weight),
                      "condition": {
                          "biomes": biomesArr
                      }
                  }
              ]
            };
            
            zip.file(
              `data/${NAMESPACE}/spawn_pool_world/${filename}`,
              JSON.stringify(spawnConfig, null, 2)
            );
            pkmnAllowedCount++;
            pkmnCount++;
          }
        });
      }

      showToast('📦', `Generando Pack (${packItems.length} ítems, ${pkmnCount} pokémon)…`);

      const blob = await zip.generateAsync({ type: 'blob' });
      const a    = document.createElement('a');
      a.href     = URL.createObjectURL(blob);
      a.download = PACK_ZIP_NAME;
      a.click();
      URL.revokeObjectURL(a.href);

      showToast('✅', `Pack generado! ${recipeCount} req, ${dropCount} drops, ${pkmnCount} pokémon`);

    } catch (err) {
      console.error('[CobblemonStudio] Error generando ZIP:', err);
      showToast('❌', 'Error al generar el Pack. Ver consola.');
    }
  });

  // ============================================================
  // INICIALIZACIÓN
  // ============================================================
  renderList();
  lucide.createIcons();
});
